// Generated by Selenium IDE
import org.junit.Test;
import org.junit.Before;
import org.junit.After;
import static org.junit.Assert.*;
import static org.hamcrest.CoreMatchers.is;
import static org.hamcrest.core.IsNot.not;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.remote.RemoteWebDriver;
import org.openqa.selenium.remote.DesiredCapabilities;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.interactions.Actions;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.WebDriverWait;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.Alert;
import org.openqa.selenium.Keys;
import java.util.*;
import java.net.MalformedURLException;
import java.net.URL;
public class SystemTestingVisualizzazioniScheduleVisiteCaregiverTest {
  private WebDriver driver;
  private Map<String, Object> vars;
  JavascriptExecutor js;
  @Before
  public void setUp() {
    driver = new ChromeDriver();
    js = (JavascriptExecutor) driver;
    vars = new HashMap<String, Object>();
  }
  @After
  public void tearDown() {
    driver.quit();
  }
  @Test
  public void systemTestingVisualizzazioniScheduleVisiteCaregiver() {
    driver.get("http://localhost:3000/HomeCaregiver");
    driver.manage().window().setSize(new Dimension(1016, 721));
    driver.findElement(By.cssSelector("#\\32 > span")).click();
    driver.findElement(By.cssSelector("div:nth-child(1) > div > .cardPazienteHomeMedico:nth-child(1) .buttonVisualizzaFascicolo")).click();
    {
      WebElement element = driver.findElement(By.cssSelector("div:nth-child(1) > div > .cardPazienteHomeMedico:nth-child(1) .buttonVisualizzaFascicolo"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).perform();
    }
    {
      WebElement element = driver.findElement(By.tagName("body"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element, 0, 0).perform();
    }
    driver.findElement(By.cssSelector("div:nth-child(1) > .bloccoMisurazione > .contenitoreMisurazione:nth-child(1) > .contenitoreDati")).click();
    driver.findElement(By.cssSelector(".react-responsive-modal-closeButton > svg")).click();
    driver.findElement(By.cssSelector("div:nth-child(3) > div > .cardPazienteHomeMedico .buttonVisualizzaFascicolo")).click();
    driver.findElement(By.cssSelector(".contenitoreMisurazioni > div:nth-child(2) > h2")).click();
    driver.findElement(By.cssSelector(".react-responsive-modal-closeButton > svg")).click();
  }
}
