package c15.dev.systemTesting;// Generated by Selenium IDE
import org.junit.Test;
import org.junit.Before;
import org.junit.After;
import static org.junit.Assert.*;
import static org.hamcrest.CoreMatchers.is;
import static org.hamcrest.core.IsNot.not;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.remote.RemoteWebDriver;
import org.openqa.selenium.remote.DesiredCapabilities;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.interactions.Actions;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.WebDriverWait;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.Alert;
import org.openqa.selenium.Keys;
import java.util.*;
import java.net.MalformedURLException;
import java.net.URL;
public class SystemTestingLoginCaregiverTest {
  private WebDriver driver;
  private Map<String, Object> vars;
  JavascriptExecutor js;
  @Before
  public void setUp() {
    driver = new ChromeDriver();
    js = (JavascriptExecutor) driver;
    vars = new HashMap<String, Object>();
  }
  @After
  public void tearDown() {
    driver.quit();
  }
  @Test
  public void systemTestingLoginCaregiver() {
    driver.get("http://localhost:3000/");
    driver.manage().window().setSize(new Dimension(1016, 721));
    driver.findElement(By.cssSelector(".formEditText:nth-child(1)")).click();
    driver.findElement(By.cssSelector(".formEditText:nth-child(1)")).sendKeys("zoccolaaless@gmail.com");
    driver.findElement(By.cssSelector(".formEditText:nth-child(2)")).click();
    driver.findElement(By.cssSelector(".formEditText:nth-child(2)")).sendKeys("Wpasswd1!%");
    driver.findElement(By.cssSelector(".formButton")).click();
    driver.findElement(By.cssSelector(".cardPazienteHomeMedico:nth-child(1) .buttonVisualizzaFascicolo")).click();
    driver.findElement(By.cssSelector(".react-responsive-modal-closeButton path")).click();
  }
}
